### ISSUE TITLE
Evaluate impact of Related-Key Attacks against ECDSA-BlindKeySign

### ISSUE THREAD

**Issue by FredericJacobs** [cfrg/draft-irtf-cfrg-signature-key-blinding#14]
We need more security analysis on ECDSA-BlindKeySign and related functions. There might be some risks related to the blinding we need to dig deeper into.

[This paper](https://eprint.iacr.org/2015/1135.pdf) Sec 4.2 doesn't directly translate to our scheme but it could be that similar attacks apply.

**Comment by chris-wood** [comment]
> We need more security analysis on ECDSA-BlindKeySign and related functions. There might be some risks related to the blinding we need to dig deeper into.

Hmm, can you elaborate on this? A blinded signing key is indistinguishable and independently distributed from the unblinded signing key, so I'm not sure I see a problem here.

**Comment by tedeaton** [comment]
I think this paper (in particular section 4.1) does point out a potential avenue of attack, especially on additive blinding (as mentioned in #2 ). The attack would allow an adversary (who knows the blinding factor) to take a message-signature pair issued under a blinded public key blpk, and transform it into a valid message-signature pair under the identity public key (or possibly under another blinded public key?).

This came up in a construction of a lattice based blinding scheme [I worked on](https://eprint.iacr.org/2021/963.pdf), which also used an 'additive' blinding method. The solution we used there should also here, which is to include the public key in the hash function when generating the challenge. Thankfully, EdDSA already does this, which should make signatures significantly more immune to this kind of malleability.

**Comment by chris-wood** [comment]
> I think this paper (in particular section 4.1) does point out a potential avenue of attack, especially on additive blinding (as mentioned in https://github.com/chris-wood/draft-wood-cfrg-eddsa-blinding/issues/2 ). The attack would allow an adversary (who knows the blinding factor) to take a message-signature pair issued under a blinded public key blpk, and transform it into a valid message-signature pair under the identity public key (or possibly under another blinded public key?).

This is only for additive blinding, correct? The draft here only discusses multiplicative blinding.

**Comment by tedeaton** [comment]
Yes, the attack as described there would only be for additive blinding, and it isn't obvious (to me) how it could be adapted for multiplicative.

**Comment by chris-wood** [comment]
@tlepoint do you think we can close this?

**Comment by chris-wood** [comment]
Closing.
