### ISSUE TITLE
Key blinding spec should specify serialization scheme

### ISSUE THREAD

**Issue by cathieyun** [cfrg/draft-irtf-cfrg-signature-key-blinding#42]
Currently, there is no serialization scheme specified for the messages being sent, or the test vectors. Specifying a serialization scheme is important for interoperability and correctness (eg using a constant-length serialization scheme if concatenating multiple serialized elements).

The OPRFs spec has a good example of serialization specifications, eg:
https://cfrg.github.io/draft-irtf-cfrg-voprf/draft-irtf-cfrg-voprf.html#name-oprfp-384-sha-384

**Comment by chris-wood** [comment]
Fixed by #43.
